from roman_numerals import to_roman

print(to_roman(1) == 'I')
print(to_roman(3) == 'III')
print(to_roman(4) == 'IV')
print(to_roman(9) == 'IX')
print(to_roman(10) == 'X')
print(to_roman(40) == 'XL')
print(to_roman(50) == 'L')
print(to_roman(90) == 'XC')
print(to_roman(100) == 'C')
print(to_roman(400) == 'CD')
print(to_roman(500) == 'D')
print(to_roman(900) == 'CM')
print(to_roman(1000) == 'M')
print(to_roman(959) == 'CMLIX')
